<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Npgsql" Version="10.0.0" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Views\Shared\package.json" />
      <_ContentIncludedByDefault Remove="Views\Account\Login.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Account\Register.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Shared\_Layout.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Wishlist\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Wishlist\Trash.cshtml" />
      <_ContentIncludedByDefault Remove="Views\_ViewImports.cshtml" />
      <_ContentIncludedByDefault Remove="wwwroot\css\site.css" />
    </ItemGroup>

</Project>
